apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: java-prom-29524
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-prom-29524 
  name: java-prom-29524
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: java-prom-29524 
